services:
  app:
    container_name: app
    build: .
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
  db:
    container_name: db
    image: postgres
    build: ./db
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pglogs:/var/log/postgresql
volumes:
  pgdata:
  pglogs:
